INSERT INTO artiste (nom, prenom, nom_scene, date_naissance, date_mort, photo, type_artiste, style_musical) VALUES ("Le Wanksi", "Le Wanksi", "Le Wanksi", '2000-01-01', NULL, "https://i.scdn.co/image/ab6761610000e5eb88078837e4a9e9c82678479f", "artist", "acidcore");
SET @id_artiste := LAST_INSERT_ID();
INSERT INTO album (titre, date_parution) VALUES ("Écume Pastel", "2023-04-26");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Écume Pastel", "05.17", "2023-04-26", "acidcore", "https://i.scdn.co/image/ab67616d0000b273b9dbad1b23712859e98101e2", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Ecume_Pastel_Le_Wanksi_Ecume_Pastel.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Mnémosyne", "2023-04-26");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Mnémosyne", "07.22", "2023-04-26", "acidcore", "https://i.scdn.co/image/ab67616d0000b273ce46a589ea83c9abd988f1d9", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Mnemosyne_Le_Wanksi_Mnemosyne.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Cauchemar", "2023-04-06");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Cauchemar", "05.28", "2023-04-06", "acidcore", "https://i.scdn.co/image/ab67616d0000b27326423e42506cb5e63f85a726", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Cauchemar_Le_Wanksi_Cauchemar.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Lune", "2023-03-20");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Lune", "07.22", "2023-03-20", "acidcore", "https://i.scdn.co/image/ab67616d0000b273d727b7dba196b775797582e3", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Lune_Le_Wanksi_Lune.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("L'Épidémie Dansante", "2023-03-17");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi L'Épidémie Dansante", "05.29", "2023-03-17", "acidcore", "https://i.scdn.co/image/ab67616d0000b273ae2c6d357c24ed5a95f5f0cb", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/L_Epidemie_Dansante_Le_Wanksi_L_Epidemie_Dansante.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
