INSERT INTO artiste (nom, prenom, nom_scene, date_naissance, date_mort, photo, type_artiste, style_musical) VALUES ("Le Wanksi", "Le Wanksi", "Le Wanksi", '2000-01-01', NULL, "https://i.scdn.co/image/ab6761610000e5eb88078837e4a9e9c82678479f", "artist", "acidcore");
SET @id_artiste := LAST_INSERT_ID();
INSERT INTO album (titre, date_parution) VALUES ("Écume Pastel", "2023-04-26");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, style_musical, emplacement_morceau) VALUES ("Écume Pastel", "05.17", "acidcore", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Ecume_Pastel_Ecume_Pastel.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Mnémosyne", "2023-04-26");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
