INSERT INTO artiste (nom, prenom, nom_scene, date_naissance, date_mort, photo, type_artiste, style_musical) VALUES ("Le Wanksi", "Le Wanksi", "Le Wanksi", '2000-01-01', NULL, "https://i.scdn.co/image/ab6761610000e5eb88078837e4a9e9c82678479f", "artist", "acidcore");
SET @id_artiste := LAST_INSERT_ID();
INSERT INTO album (titre, date_parution) VALUES ("Écume Pastel", "2023-04-26");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Écume Pastel", "05.17", "2023-04-26", "acidcore", "https://i.scdn.co/image/ab67616d0000b273b9dbad1b23712859e98101e2", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Ecume_Pastel_Le_Wanksi_Ecume_Pastel.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Mnémosyne", "2023-04-26");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Mnémosyne", "07.22", "2023-04-26", "acidcore", "https://i.scdn.co/image/ab67616d0000b273ce46a589ea83c9abd988f1d9", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Mnemosyne_Le_Wanksi_Mnemosyne.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Cauchemar", "2023-04-06");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Cauchemar", "05.28", "2023-04-06", "acidcore", "https://i.scdn.co/image/ab67616d0000b27326423e42506cb5e63f85a726", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Cauchemar_Le_Wanksi_Cauchemar.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Lune", "2023-03-20");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Lune", "07.22", "2023-03-20", "acidcore", "https://i.scdn.co/image/ab67616d0000b273d727b7dba196b775797582e3", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Lune_Le_Wanksi_Lune.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("L'Épidémie Dansante", "2023-03-17");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi L'Épidémie Dansante", "05.29", "2023-03-17", "acidcore", "https://i.scdn.co/image/ab67616d0000b273ae2c6d357c24ed5a95f5f0cb", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/L_Epidemie_Dansante_Le_Wanksi_L_Epidemie_Dansante.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Ça Monte", "2023-03-14");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Ça Monte", "06.40", "2023-03-14", "acidcore", "https://i.scdn.co/image/ab67616d0000b2733798f0c3b6e6bd98e9743064", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Ca_Monte_Le_Wanksi_Ca_Monte.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("revêR", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi revêR", "07.41", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2734ad6df469b918f4d0168ad75", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/reveR_Le_Wanksi_reveR.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Wailing", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Wailing", "04.04", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273282b64d5c4254c5802495e18", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Wailing_Le_Wanksi_Wailing.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Vie", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Vie", "04.30", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273051feff6ebd5b7ea21bef237", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Vie_Le_Wanksi_Vie.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Venin", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Venin", "06.03", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b27366ab78d9532a4aa4330233f1", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Venin_Le_Wanksi_Venin.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("VHS Rave", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi VHS Rave", "05.18", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2731b2f100766930bc5ca796050", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/VHS_Rave_Le_Wanksi_VHS_Rave.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Un Petit Peu", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Un Petit Peu", "04.30", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2734e146b2467cb00e3232f73a8", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Un_Petit_Peu_Le_Wanksi_Un_Petit_Peu.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Temps De Cerveau Disponible", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Temps De Cerveau Disponible", "07.40", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273dc196cc988ab74d407db33d0", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Temps_De_Cerveau_Disponible_Le_Wanksi_Temps_De_Cerveau_Disponible.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Tarte à la myrtille", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Tarte à la myrtille", "06.40", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273cc2ea5ca6c8591f602702c86", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Tarte_a_la_myrtille_Le_Wanksi_Tarte_a_la_myrtille.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Tape Des Pieds", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Tape Des Pieds", "03.27", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2730fa23e37437a46fba230a4d5", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Tape_Des_Pieds_Le_Wanksi_Tape_Des_Pieds.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Sois Méchant, Pas Gentil", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Sois Méchant, Pas Gentil", "04.50", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b27304f6b55aed6b905f7679a634", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Sois_Mechant__Pas_Gentil_Le_Wanksi_Sois_Mechant__Pas_Gentil.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("She Babao", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi She Babao", "03.54", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273c25b9fafc916ea1fefcaca65", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/She_Babao_Le_Wanksi_She_Babao.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Psychotic", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Psychotic", "04.04", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273d95176ad1058f45a58ef1a94", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Psychotic_Le_Wanksi_Psychotic.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Psychonautes", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Psychonautes", "07.43", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273052ba7ddd3e2d3554404277c", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Psychonautes_Le_Wanksi_Psychonautes.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Poule Renard Vipère", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Poule Renard Vipère", "05.31", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273a8a021ef595de40cffc6700b", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Poule_Renard_Vipere_Le_Wanksi_Poule_Renard_Vipere.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Mangala", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Mangala", "06.24", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2732d024aedcb13bfee6a85b342", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Mangala_Le_Wanksi_Mangala.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Maman va gueuler", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Maman va gueuler", "06.01", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273d4d10df2ac70da05fc4b8595", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Maman_va_gueuler_Le_Wanksi_Maman_va_gueuler.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("M.U.S.H", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi M.U.S.H", "07.22", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273abc3cbc5740cb6a39c5195bd", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/M_U_S_H_Le_Wanksi_M_U_S_H.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Les petits bonbons anglais", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Les petits bonbons anglais", "06.12", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273a94edf6d2d0684d2f01f247c", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Les_petits_bonbons_anglais_Le_Wanksi_Les_petits_bonbons_anglais.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Le Teufeur Du Grenier", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Le Teufeur Du Grenier", "05.47", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b27309e58acc05041030534981cf", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Le_Teufeur_Du_Grenier_Le_Wanksi_Le_Teufeur_Du_Grenier.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Le Temps", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Le Temps", "06.11", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2737eff7cc64a35eea0a4271995", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Le_Temps_Le_Wanksi_Le_Temps.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("La Dune Aux Épaves", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi La Dune Aux Épaves", "05.44", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273aee145253f734132cd5c72fd", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/La_Dune_Aux_Epaves_Le_Wanksi_La_Dune_Aux_Epaves.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("La Couleur Du Son", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi La Couleur Du Son", "07.03", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b27379d47fc3020660c10147e924", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/La_Couleur_Du_Son_Le_Wanksi_La_Couleur_Du_Son.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("L'Ivresse Des Montagnes", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi L'Ivresse Des Montagnes", "05.49", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b27384f3d01dad78afccf82a70e3", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/L_Ivresse_Des_Montagnes_Le_Wanksi_L_Ivresse_Des_Montagnes.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Intelligence Artificielle", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Intelligence Artificielle", "06.34", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273153b282cccb83ac87d0e0967", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Intelligence_Artificielle_Le_Wanksi_Intelligence_Artificielle.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Herbe Lactée", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Herbe Lactée", "06.58", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273d63926feac2e3e7b83aa7b31", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Herbe_Lactee_Le_Wanksi_Herbe_Lactee.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Gesaffelstek", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Gesaffelstek", "05.55", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2732e4715ace4b06730401c744c", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Gesaffelstek_Le_Wanksi_Gesaffelstek.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Est-ce que tu veux un ballon ?", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Est-ce que tu veux un ballon ?", "04.30", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273522005ee71d81f217cd7bf55", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Est-ce_que_tu_veux_un_ballon___Le_Wanksi_Est-ce_que_tu_veux_un_ballon__.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Esprit Éveillé, Corps Endormi", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Esprit Éveillé, Corps Endormi", "05.59", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273b0bd48d6033d254b264023c1", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Esprit_Eveille__Corps_Endormi_Le_Wanksi_Esprit_Eveille__Corps_Endormi.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Du Sale", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Du Sale", "04.30", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273e6e4872b8509f5097483869d", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Du_Sale_Le_Wanksi_Du_Sale.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Dimensions", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Dimensions", "07.22", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273b90bbde4419840d2701b2354", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Dimensions_Le_Wanksi_Dimensions.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Cœur De Sable", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Cœur De Sable", "05.58", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b27391d74b41383c298a5efcd161", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Coeur_De_Sable_Le_Wanksi_Coeur_De_Sable.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Consomme", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Consomme", "05.13", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273ed7b544dc0b644ec4c3f6e3b", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Consomme_Le_Wanksi_Consomme.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Clapotis", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Clapotis", "05.20", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273f4c6e04a98b2cc1436bf72c9", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Clapotis_Le_Wanksi_Clapotis.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Bleue Comme Une Orange", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Bleue Comme Une Orange", "02.32", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b27373576d0d1e9f57472ce5d4d4", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Bleue_Comme_Une_Orange_Le_Wanksi_Bleue_Comme_Une_Orange.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Bella Ciao", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Bella Ciao", "05.17", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273ae9e0e7fa15eb9fe86ebf430", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Bella_Ciao_Le_Wanksi_Bella_Ciao.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Attention zone de bruit", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Attention zone de bruit", "04.40", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2734e5b54e3ca6833cbbde0b719", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Attention_zone_de_bruit_Le_Wanksi_Attention_zone_de_bruit.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Atlantide", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Atlantide", "07.22", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b27356a9e4650701503c6e0fbcf8", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Atlantide_Le_Wanksi_Atlantide.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Aseptisés", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Aseptisés", "05.29", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b2735bc6ada67d533450ef5f97d0", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Aseptises_Le_Wanksi_Aseptises.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Arya Tara", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Arya Tara", "07.15", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273528c86495a476f25d069b882", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Arya_Tara_Le_Wanksi_Arya_Tara.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Aquabiome", "2023-03-04");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Aquabiome", "07.22", "2023-03-04", "acidcore", "https://i.scdn.co/image/ab67616d0000b273c765a7992f84bc2faf56d066", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Aquabiome_Le_Wanksi_Aquabiome.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
INSERT INTO album (titre, date_parution) VALUES ("Corrosif", "2018-12-18");
SET @id_album := LAST_INSERT_ID();
INSERT INTO a_publie (id_album, id_artiste) VALUES (@id_album, @id_artiste);
INSERT INTO morceau (titre, duree, date_parution, style_musical, emplacement, emplacement_morceau) VALUES ("Le Wanksi Corrosif", "07.15", "2018-12-18", "acidcore", "https://i.scdn.co/image/ab67616d0000b273d21f0084a53e557747dbf290", "http://prj-web-cir2-grp-58/assets/music/Le_Wanksi/Corrosif_Le_Wanksi_Corrosif.mp3");
SET @id_morceau := LAST_INSERT_ID();
INSERT INTO album_contient_morceaux (id_album, id_morceau) VALUES (@id_album, @id_morceau);
